[package]
name = "rusterizer"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16.5"
num = "0.2.0"

[dev-dependencies]
image = "0.19.0"
rand = "0.5.5"
wavefront_obj = "5.1.0"
failure = "0.1.3"
minifb = "0.11.0"
