[package]
name = "rusterizer"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.21.1"

[dev-dependencies]
image = "0.23.8"
minifb = "0.17.0"
wavefront_obj = "8.0.0"
