[package]
name = "rusterizer"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]

[dependencies]
image = "0.19.0"
nalgebra = "0.15.3"

[dev-dependencies]
rand = "0.5.3"
wavefront_obj = "5.1.0"
failure = "0.1.1"
