[package]
name = "rusterizer"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]
edition = "2018"

[dependencies]
glam = "0.13.0"

[dev-dependencies]
image = "0.23.8"
minifb = "0.19.2"
wavefront_obj = "8.0.0"
