[package]
name = "rusterizer"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16.0"
num = "0.2.0"

[dev-dependencies]
image = "0.19.0"
rand = "0.5.3"
wavefront_obj = "5.1.0"
failure = "0.1.1"
minifb = "0.10.7"
